import Link from "next/link";
import { Container } from "@/components/ui/container";
import { buttonVariants } from "@/components/ui/button-variants";
import { ROUTES } from "@/constants/routes";

// Multi-accent per stage (Hum signature move #2: section bands) — each
// phase owns its own surface rather than one accent flooding the page.
const PHASES = [
  {
    number: "1.0",
    title: "Job description + company",
    body: "You give us the job description, the company's site, and how many days you have until the interview. Nothing is inferred beyond what you provide.",
    badge: "bg-accent text-ink",
    band: "bg-accent-bg",
  },
  {
    number: "2.0",
    title: "Company research",
    body: "We read the company's own public pages — about, product, careers where one exists — and summarise only what's actually there. No hiring page found is reported honestly, not papered over.",
    badge: "bg-cyan text-paper",
    band: "bg-cyan-bg",
  },
  {
    number: "3.0",
    title: "Requirements, extracted",
    body: "The job description is parsed into individual requirements, each marked must-have or nice-to-have. We don't invent a requirement the posting doesn't support.",
    badge: "bg-coral text-paper",
    band: "bg-coral-bg",
  },
  {
    number: "4.0",
    title: "Questions and flashcards",
    body: "Interview questions are generated by category — technical, behavioural, system design, company fit — then checked against the requirements. Anything missed gets a second, targeted pass.",
    badge: "bg-mint text-ink",
    band: "bg-mint-bg",
  },
  {
    number: "5.0",
    title: "A schedule sized to your timeline",
    body: "The harder and higher-priority material is placed earlier. The schedule always has exactly as many days as you asked for — never more, never fewer.",
    badge: "bg-lavender text-ink",
    band: "bg-lavender-bg",
  },
];

export default function HomePage() {
  return (
    <>
      {/* Off-centre hero — Hum's most-banned tell is the centred stack, so
          the headline stays left-aligned with the CTA breaking left too. */}
      <Container width="default" className="flex flex-col gap-6 py-20 sm:py-28">
        <h1 className="max-w-2xl text-4xl text-ink sm:text-display-s">
          Interview prep, built from <em>evidence</em>.
        </h1>
        <p className="max-w-prose text-lg text-neutral">
          Give InsightPrep a job description and a company. It researches what&apos;s real, extracts what the role
          actually asks for, and builds a study kit around it — questions, flashcards, and a day-by-day schedule.
        </p>
        <div>
          <Link href={ROUTES.register} className={buttonVariants("primary", "btn--lg")}>
            Create your first kit
          </Link>
        </div>
      </Container>

      {/* Narrative Workflow: each stage is a colour-shift card on its own
          accent band, connected by a rail — the sequence IS the structure. */}
      <Container width="default" className="flex flex-col gap-6 py-10 sm:py-16">
        {PHASES.map((phase, index) => (
          <div
            key={phase.number}
            className={`flex flex-col gap-4 rounded-(--radius-card) p-6 transition-all duration-200 ease-(--ease-spring) hover:-translate-y-1 hover:shadow-lg sm:flex-row sm:gap-8 sm:p-8 ${phase.band}`}
          >
            <div className="flex items-center gap-4 sm:flex-col sm:items-start sm:gap-2">
              <span
                className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-full font-data text-sm font-medium ${phase.badge}`}
              >
                {phase.number}
              </span>
              {index < PHASES.length - 1 && (
                <span aria-hidden="true" className="hidden h-full w-px border-l-[1.5px] border-dashed border-rule sm:block" />
              )}
            </div>
            <div className="flex flex-col gap-2">
              <h2 className="text-xl text-ink">{phase.title}</h2>
              <p className="max-w-prose text-neutral">{phase.body}</p>
            </div>
          </div>
        ))}
      </Container>

      <Container width="default" className="flex flex-col items-start gap-4 py-20">
        <h2 className="text-2xl text-ink">Start with what you already have.</h2>
        <Link href={ROUTES.register} className={buttonVariants("primary", "btn--lg")}>
          Create your first kit
        </Link>
      </Container>
    </>
  );
}
